### ISSUE TITLE
TypeError: container[0] is undefined[Learn More] reveal-svg-fragment.js:42:7

### ISSUE THREAD

**Issue by deisi** [csachs/reveal-svg-fragment#1]
As already posted in the [gist](https://gist.github.com/bollwyvl/fe1d2806449487cdf88a) there seems to be something wrong.
I use firefox: 63.0.1
on arch-linux

**Comment by csachs** [comment]
Hi. Unfortunately I can't reproduce the issue with Firefox 62.0.3, 63.0.1 (64-bit, Windows) and 63.0.0 (64-bit, Linux, Ubuntu). How are you serving the example, via a web server? Any other errors in the console which could help to pinpoint this problem? Is Reveal in the demo working otherwise?

**Comment by deisi** [comment]
I use a docker container.
Here is the DOCKERFILE for the image:
https://github.com/deisi/reveal.js-docker

And then I run it with docker-compose looking like:
```
revealjs:
  image: id_of_image
  ports:
    - "8000:8000"
    - "35729:35729"
  volumes:
   - /path/to/presentations:/revealjs/presentations
```

>  Is Reveal in the demo working otherwise?

Yep the rest is working. I copied the demo in my presentation folder.

> ny other errors in the console which could help to pinpoint this problem?

The full error log is:
```
TypeError: container[0] is undefined[Learn More] reveal-svg-fragment.js:42:7
api/<
http://localhost:8000/presentations/fe1d2806449487cdf88a-9ab4c5e38f1ea68b3afaf0c1dee998a89229a8d4/reveal-svg-fragment.js:42:7
Gf
http://cdn.jsdelivr.net/d3js/latest/d3.min.js:4:26660
api
http://localhost:8000/presentations/fe1d2806449487cdf88a-9ab4c5e38f1ea68b3afaf0c1dee998a89229a8d4/reveal-svg-fragment.js:41:5
finish
http://localhost:8000/presentations/fe1d2806449487cdf88a-9ab4c5e38f1ea68b3afaf0c1dee998a89229a8d4/reveal-svg-fragment.js:167:9
```

**Comment by csachs** [comment]
Weird. I have cloned your repository, built the docker image, and started a container using it.
The reveal-svg-fragment works within the example, and added to your `index.html` (which btw lacks a `{` in https://github.com/deisi/reveal.js-docker/blob/master/demo_presentation/index.html#L241 ).

**Oh, wait a second**… are you using the original version from the gist or the fixed version from this repository? The line `http://cdn.jsdelivr.net/d3js/latest/d3.min.js` in your stack trace looks like it is the gist version (which is not working, which is why I made this repository…).

**Comment by deisi** [comment]
ah I think I use the gist I check out the repo and thx for the bugreport in the demo.

**Comment by deisi** [comment]
Ah now it works. Thx a lot.

**Comment by csachs** [comment]
You're welcome.
